// components/layout/Navbar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import { ThemeToggle } from "./ThemeToggle";
import { Button } from "@/components/shared/Button";
import { logoutAction } from "@/app/actions/auth";
import type { Session } from "@/lib/auth";

const publicLinks = [
  { href: "/", label: "Home" },
  { href: "/gallery", label: "Gallery" },
  { href: "/collections", label: "Collections" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
];

const authLinks = [
  { href: "/favourites", label: "Favourites" },
  { href: "/payment", label: "Payments" },
];

function isActive(pathname: string, href: string) {
  return href === "/" ? pathname === "/" : pathname.startsWith(href);
}

export function Navbar({ session }: { session: Session | null }) {
  const pathname = usePathname();
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);
  const links = session ? [...publicLinks, ...authLinks] : publicLinks;

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 12);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  // Lock body scroll while the full-screen mobile menu is open.
  useEffect(() => {
    if (open) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [open]);

  return (
    <header className="fixed inset-x-0 top-0 z-50 flex justify-center px-3 pt-3 sm:px-6">
      <motion.nav
        initial={{ y: -24, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        className={cn(
          "flex w-full max-w-7xl items-center justify-between rounded-full px-3 py-1.5 sm:px-4 transition-all duration-300",
          scrolled
            ? "glass shadow-card-hover"
            : "border border-transparent bg-transparent"
        )}
      >
        <Link
          href="/"
          className="group flex items-center gap-2 rounded-full px-2 py-1 font-semibold tracking-tight"
        >
          <span className="grid h-8 w-8 place-items-center rounded-lg bg-accent text-white shadow-lg shadow-accent/30 transition-transform duration-300 group-hover:scale-105 group-hover:shadow-glow">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
              <circle cx="12" cy="13" r="4" />
            </svg>
          </span>
          <span className="text-lg">Lumen</span>
        </Link>

        <div className="hidden items-center gap-1 md:flex">
          {links.map((l) => {
            const active = isActive(pathname, l.href);
            return (
              <Link
                key={l.href}
                href={l.href}
                className={cn(
                  "group relative rounded-full px-4 py-2 text-sm font-medium transition-colors duration-200",
                  active ? "text-fg" : "text-muted hover:text-fg"
                )}
              >
                {l.label}
                <span
                  className={cn(
                    "absolute -bottom-0.5 left-1/2 h-1 w-1 -translate-x-1/2 rounded-full bg-accent transition-all duration-300",
                    active
                      ? "scale-100 opacity-100 shadow-glow-sm"
                      : "scale-0 opacity-0 group-hover:scale-75 group-hover:opacity-50"
                  )}
                />
              </Link>
            );
          })}
          <div className="mx-1 h-5 w-px bg-border-40" />
          <ThemeToggle />
          <div className="ml-1 flex items-center gap-2">
            {session ? (
              <form action={logoutAction}>
                <button
                  type="submit"
                  className="rounded-full border border-border bg-surface-65 px-4 py-2 text-sm font-medium transition-all duration-200 hover:border-accent/60 hover:text-accent hover:shadow-glow-sm focus-glow active:scale-[0.98]"
                >
                  {session.role === "admin" ? "Admin · Log out" : "Log out"}
                </button>
              </form>
            ) : (
              <Button href="/login" size="sm">
                Log in
              </Button>
            )}
          </div>
        </div>

        <div className="flex items-center gap-2 md:hidden">
          <ThemeToggle />
          <button
            type="button"
            aria-label="Toggle menu"
            aria-expanded={open}
            onClick={() => setOpen((v) => !v)}
            className="grid h-9 w-9 place-items-center rounded-full border border-border bg-surface-65 text-fg transition-colors hover:bg-surface-2"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
              {open ? <path d="M18 6 6 18M6 6l12 12" /> : <path d="M3 6h18M3 12h18M3 18h18" />}
            </svg>
          </button>
        </div>
      </motion.nav>

      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="glass-elevated fixed inset-0 z-40 flex flex-col px-6 pb-10 pt-24 sm:px-10"
          >
            <nav className="flex flex-col gap-1">
              {links.map((l, i) => {
                const active = isActive(pathname, l.href);
                return (
                  <motion.div
                    key={l.href}
                    initial={{ opacity: 0, y: 18 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: 10 }}
                    transition={{
                      delay: 0.08 + 0.06 * i,
                      duration: 0.4,
                      ease: [0.16, 1, 0.3, 1],
                    }}
                  >
                    <Link
                      href={l.href}
                      onClick={() => setOpen(false)}
                      className={cn(
                        "block border-b border-border-25 py-4 font-display text-3xl font-semibold tracking-tight transition-colors duration-200",
                        active ? "text-accent" : "text-fg hover:text-accent"
                      )}
                    >
                      {l.label}
                    </Link>
                  </motion.div>
                );
              })}
            </nav>

            <motion.div
              initial={{ opacity: 0, y: 18 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              transition={{ delay: 0.08 + 0.06 * links.length, duration: 0.4 }}
              className="mt-auto"
            >
              {session ? (
                <form action={logoutAction}>
                  <button
                    type="submit"
                    className="w-full rounded-2xl border border-border bg-surface-65 px-4 py-4 text-center text-base font-semibold transition-colors hover:text-accent focus-glow active:scale-[0.98]"
                  >
                    {session.role === "admin" ? "Admin · Log out" : "Log out"}
                  </button>
                </form>
              ) : (
                <Link
                  href="/login"
                  onClick={() => setOpen(false)}
                  className="block rounded-2xl bg-accent px-4 py-4 text-center text-base font-semibold text-white shadow-lg shadow-accent/30 transition-all duration-200 hover:-translate-y-0.5 hover:shadow-glow focus-glow active:scale-[0.98]"
                >
                  Log in
                </Link>
              )}
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </header>
  );
}

// apps/lumen/src/app/shared/components/layout/navbar.component.ts
import { Component, HostBinding, Input, inject, signal, HostListener, OnDestroy } from '@angular/core';
import { RouterLink, RouterLinkActive, Router, NavigationEnd } from '@angular/router';
import { CommonModule } from '@angular/common';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { filter } from 'rxjs';
import { AuthService } from '../../../core/services/auth.service';
import { ThemeService } from '../../../core/services/theme.service';
import { ThemeToggleComponent } from '../theme/theme-toggle.component';
import { ButtonComponent } from '../button.component';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, ThemeToggleComponent, ButtonComponent],
  template: `
    <header class="fixed top-0 left-0 right-0 z-50 glass border-b border-border-25">
      <nav class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8" aria-label="Main navigation">
        <div class="flex h-16 items-center justify-between">
          <div class="flex items-center">
            <a routerLink="/" class="font-display text-h3 font-semibold tracking-tight text-fg" aria-label="Lumen home">
              Lumen
            </a>
          </div>

          <div class="hidden md:flex md:items-center md:gap-8">
            <a routerLink="/gallery" routerLinkActive="text-accent" class="text-sm font-medium text-muted transition-colors hover:text-fg">Gallery</a>
            <a routerLink="/collections" routerLinkActive="text-accent" class="text-sm font-medium text-muted transition-colors hover:text-fg">Collections</a>
            <a routerLink="/about" routerLinkActive="text-accent" class="text-sm font-medium text-muted transition-colors hover:text-fg">About</a>
            <a routerLink="/contact" routerLinkActive="text-accent" class="text-sm font-medium text-muted transition-colors hover:text-fg">Contact</a>
          </div>

          <div class="flex items-center gap-4">
            <app-theme-toggle />

            <div class="hidden md:flex md:items-center md:gap-4">
              @if (authService.session(); as session) {
                <a routerLink="/favourites" class="text-sm font-medium text-muted transition-colors hover:text-fg">Favourites</a>
                <a routerLink="/payment" class="text-sm font-medium text-muted transition-colors hover:text-fg">Purchases</a>
                @if (session.role === 'admin') {
                  <a routerLink="/admin" class="text-sm font-medium text-muted transition-colors hover:text-fg">Admin</a>
                }
                <button (click)="logout()" class="text-sm font-medium text-muted transition-colors hover:text-fg">Logout</button>
              } @else {
                <a routerLink="/login" class="text-sm font-medium text-muted transition-colors hover:text-fg">Login</a>
                <app-button variant="primary" [routerLink]="['/signup']">Sign up</app-button>
              }
            </div>

            <!-- Mobile menu toggle -->
            <button
              type="button"
              class="md:hidden inline-flex items-center justify-center rounded-md p-2 text-muted transition-colors hover:text-fg focus:outline-none focus:ring-2 focus:ring-accent"
              [attr.aria-expanded]="mobileOpen()"
              aria-controls="mobile-menu"
              [attr.aria-label]="mobileOpen() ? 'Close menu' : 'Open menu'"
              (click)="mobileOpen.set(!mobileOpen())"
            >
              @if (mobileOpen()) {
                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
              } @else {
                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" /></svg>
              }
            </button>
          </div>
        </div>
      </nav>

      <!-- Mobile slide-down panel -->
      @if (mobileOpen()) {
        <div id="mobile-menu" class="md:hidden glass border-t border-border-25 animate-fade-in">
          <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 flex flex-col gap-1">
            <a routerLink="/gallery" routerLinkActive="text-accent" (click)="close()" class="rounded-md px-3 py-2 text-base font-medium text-muted transition-colors hover:text-fg hover:bg-surface-2">Gallery</a>
            <a routerLink="/collections" routerLinkActive="text-accent" (click)="close()" class="rounded-md px-3 py-2 text-base font-medium text-muted transition-colors hover:text-fg hover:bg-surface-2">Collections</a>
            <a routerLink="/about" routerLinkActive="text-accent" (click)="close()" class="rounded-md px-3 py-2 text-base font-medium text-muted transition-colors hover:text-fg hover:bg-surface-2">About</a>
            <a routerLink="/contact" routerLinkActive="text-accent" (click)="close()" class="rounded-md px-3 py-2 text-base font-medium text-muted transition-colors hover:text-fg hover:bg-surface-2">Contact</a>

            <div class="my-2 h-px bg-border-25"></div>

            @if (authService.session(); as session) {
              <a routerLink="/favourites" (click)="close()" class="rounded-md px-3 py-2 text-base font-medium text-muted transition-colors hover:text-fg hover:bg-surface-2">Favourites</a>
              <a routerLink="/payment" (click)="close()" class="rounded-md px-3 py-2 text-base font-medium text-muted transition-colors hover:text-fg hover:bg-surface-2">Purchases</a>
              @if (session.role === 'admin') {
                <a routerLink="/admin" (click)="close()" class="rounded-md px-3 py-2 text-base font-medium text-muted transition-colors hover:text-fg hover:bg-surface-2">Admin</a>
              }
              <button (click)="close(); logout()" class="rounded-md px-3 py-2 text-left text-base font-medium text-muted transition-colors hover:text-fg hover:bg-surface-2">Logout</button>
            } @else {
              <a routerLink="/login" (click)="close()" class="rounded-md px-3 py-2 text-base font-medium text-muted transition-colors hover:text-fg hover:bg-surface-2">Login</a>
              <app-button variant="primary" [routerLink]="['/signup']" (clicked)="close()" class="mt-1 w-full justify-center">Sign up</app-button>
            }
          </div>
        </div>
      }
    </header>
  `,
  styles: []
})
export class NavbarComponent implements OnDestroy {
  @HostBinding('class') class = 'w-full';
  authService = inject(AuthService);
  themeService = inject(ThemeService);
  private router = inject(Router);

  mobileOpen = signal(false);

  constructor() {
    // Close the mobile panel whenever navigation completes.
    this.router.events.pipe(
      filter((e): e is NavigationEnd => e instanceof NavigationEnd),
      takeUntilDestroyed()
    ).subscribe(() => this.mobileOpen.set(false));
  }

  ngOnDestroy() {
    this.mobileOpen.set(false);
  }

  close() {
    this.mobileOpen.set(false);
  }

  @HostListener('document:keydown.escape')
  onEscape() {
    if (this.mobileOpen()) this.mobileOpen.set(false);
  }

  logout() {
    this.authService.logout().subscribe();
  }
}
