// components/gallery/PhotoCard.tsx
"use client";

import Image from "next/image";
import type { Photo } from "@/lib/storage/types";

interface Props {
  photo: Photo;
  onOpen: (photo: Photo) => void;
  sizes?: string;
  priority?: boolean;
}

export function PhotoCard({ photo, onOpen, sizes, priority }: Props) {
  return (
    <button
      type="button"
      onClick={() => onOpen(photo)}
      className="group relative mb-4 block w-full overflow-hidden rounded-2xl border border-border bg-surface"
      aria-label={`Open ${photo.title ?? photo.alt}`}
    >
      <Image
        src={photo.src}
        alt={photo.alt}
        width={photo.width}
        height={photo.height}
        placeholder={photo.blurDataURL ? "blur" : "empty"}
        blurDataURL={photo.blurDataURL}
        sizes={sizes ?? "(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"}
        priority={priority}
        className="h-auto w-full object-cover transition-transform duration-500 group-hover:scale-[1.04]"
      />
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
      {photo.title && (
        <span className="pointer-events-none absolute bottom-3 left-3 right-3 translate-y-2 text-sm font-medium text-white opacity-0 transition-all duration-300 group-hover:translate-y-0 group-hover:opacity-100">
          {photo.title}
        </span>
      )}
    </button>
  );
}

// apps/lumen/src/app/shared/components/gallery/photo-card.component.ts
import { Component, Input, Output, EventEmitter, inject, PLATFORM_ID, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { Photo } from '../../../core/services/photo.service';
import { PhotoService } from '../../../core/services/photo.service';

@Component({
  selector: 'app-photo-card',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <article class="group relative break-inside-avoid mb-4 overflow-hidden rounded-lg bg-surface border border-border-25 transition-all duration-300 hover:shadow-card-hover hover:-translate-y-1">
      <div
        class="relative aspect-auto min-h-[200px] overflow-hidden cursor-pointer"
        (click)="open.emit(photo)"
        (keydown.enter)="open.emit(photo)"
        (keydown.space)="open.emit(photo); $event.preventDefault()"
        tabindex="0"
        role="button"
        [attr.aria-label]="'View ' + (photo.title || photo.alt)"
      >
        <img
          [src]="photoService.getPhotoUrl(photo, 'preview')"
          [srcset]="photoService.getPhotoSrcset(photo, [640, 900, 1200])"
          sizes="(min-width: 1280px) 25vw, (min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw"
          [width]="photo.width"
          [height]="photo.height"
          [alt]="photo.alt"
          class="w-full h-auto object-cover transition-transform duration-700 group-hover:scale-105"
          loading="lazy"
          decoding="async"
          draggable="false"
          style="user-select: none"
          (contextmenu)="$event.preventDefault()"
        />
        <div class="absolute inset-0 bg-gradient-to-t from-bg/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
      </div>

      <div
        class="p-4 cursor-pointer"
        (click)="open.emit(photo)"
        tabindex="0"
        role="button"
        [attr.aria-label]="'View ' + (photo.title || photo.alt)"
      >
        <h3 class="text-sm font-medium text-fg truncate">{{ photo.title || 'Untitled' }}</h3>
        <p class="text-xs text-muted mt-0.5 truncate">{{ photo.collectionId }}</p>
      </div>
    </article>
  `,
  styles: []
})
export class PhotoCardComponent {
  @Input({ required: true }) photo!: Photo;
  @Output() open = new EventEmitter<Photo>();

  photoService = inject(PhotoService);
}
