// apps/lumen/src/app/shared/components/shared/text-reveal.component.ts
import { Component, Input, ViewChild, ElementRef, inject, PLATFORM_ID, AfterViewInit, OnDestroy } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { signal } from '@angular/core';

@Component({
  selector: 'app-text-reveal',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div #container [class]="className" [attr.tag]="tag">
      @if (split) {
        @for (line of lines; track $index) {
          <div class="overflow-hidden" [style.transition-delay.ms]="delay + $index * 100">
            <span
              [class.opacity-0]="!visibleLines()[$index]"
              [class.translate-y-full]="!visibleLines()[$index]"
              [class.opacity-100]="visibleLines()[$index]"
              [class.translate-y-0]="visibleLines()[$index]"
              class="inline-block transition-all duration-700 ease-out"
            >
              {{ line }}
            </span>
          </div>
        }
      } @else {
        <span
          [class.opacity-0]="!isVisible()"
          [class.translate-y-full]="!isVisible()"
          [class.opacity-100]="isVisible()"
          [class.translate-y-0]="isVisible()"
          class="inline-block transition-all duration-700 ease-out"
        >
          <ng-content></ng-content>
        </span>
      }
    </div>
  `,
  styles: []
})
export class TextRevealComponent implements AfterViewInit, OnDestroy {
  @ViewChild('container') containerRef!: ElementRef<HTMLElement>;
  @Input() className = '';
  @Input() delay = 0;
  @Input() tag = 'div';
  @Input() split = false;

  private platformId = inject(PLATFORM_ID);
  private isBrowser = isPlatformBrowser(this.platformId);
  private observer: IntersectionObserver | null = null;

  isVisible = signal(false);
  visibleLines = signal<boolean[]>([]);
  lines: string[] = [];

  ngAfterViewInit() {
    if (this.split) {
      const text = this.containerRef.nativeElement.textContent || '';
      this.lines = text.split('\n').filter(l => l.trim());
      this.visibleLines.set(this.lines.map(() => false));
    }

    if (!this.isBrowser) {
      this.isVisible.set(true);
      if (this.split) {
        this.visibleLines.set(this.lines.map(() => true));
      }
      return;
    }

    this.observer = new IntersectionObserver(
      (entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            setTimeout(() => {
              this.isVisible.set(true);
              if (this.split) {
                this.lines.forEach((_, i) => {
                  setTimeout(() => {
                    this.visibleLines.update(arr => {
                      const next = [...arr];
                      next[i] = true;
                      return next;
                    });
                  }, i * 100);
                });
              }
            }, this.delay);
            this.observer?.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1, rootMargin: '50px' }
    );

    this.observer.observe(this.containerRef.nativeElement);
  }

  ngOnDestroy() {
    this.observer?.disconnect();
  }
}

// src/components/ui/text-reveal.tsx
'use client';

import { type ReactNode, useState, useEffect, useRef } from 'react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

interface TextRevealProps {
  children: ReactNode;
  className?: string;
  delay?: number;
  split?: boolean;
}

export function TextReveal({ children, className, delay = 0, split = false }: TextRevealProps) {
  const ref = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);
  const [visibleLines, setVisibleLines] = useState<boolean[]>([]);
  const linesRef = useRef<string[]>([]);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    if (split) {
      const text = el.textContent || '';
      linesRef.current = text.split('\n').filter((l) => l.trim());
      setVisibleLines(linesRef.current.map(() => false));
    }

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setTimeout(() => {
              setIsVisible(true);
              if (split) {
                linesRef.current.forEach((_, i) => {
                  setTimeout(() => {
                    setVisibleLines((prev) => {
                      const next = [...prev];
                      next[i] = true;
                      return next;
                    });
                  }, i * 100);
                });
              }
            }, delay);
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1, rootMargin: '50px' }
    );

    observer.observe(el);
    return () => observer.disconnect();
  }, [split, delay]);

  if (split) {
    return (
      <div ref={ref} className={className}>
        {linesRef.current.map((line, i) => (
          <div key={i} className="overflow-hidden" style={{ transitionDelay: `${delay + i * 100}ms` }}>
            <span
              className={clsx(
                'inline-block transition-all duration-700 ease-out',
                visibleLines[i] ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-full'
              )}
            >
              {line}
            </span>
          </div>
        ))}
      </div>
    );
  }

  return (
    <div ref={ref} className={className}>
      <span
        className={clsx(
          'inline-block transition-all duration-700 ease-out',
          isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-full'
        )}
      >
        {children}
      </span>
    </div>
  );
}
